pipeline:
  build:
    image: golang
    commands:
      - cd $GOPATH
      - rm -rf *
      - wget https://raw.githubusercontent.com/tleyden/sync_gateway/blob/master/build.sh
      - cat build.sh
      - chmod +x build.sh
      - ./build.sh $$BRANCH $$COMMIT
