pipeline:
  build:
    image: golang
    commands:
      - cd $GOPATH
      - rm -rf *
      - wget https://raw.githubusercontent.com/Daninet/sync_gateway/master/build.sh
      - cat build.sh
      - chmod +x build.sh
      # - ./build.sh $$BRANCH $$COMMIT
  publish:
    image: plugins/docker
    repo: dani/dani
    tags: [ latest ]
